Add_API_Gist_GitHub
Vlad2088/test_guru pull request #13
Opened 2023-10-20 12:59 UTC by Vlad2088

2023-10-20 13:01 UTC, Vlad2088 commented on app/controllers/gists_controller.rb
> +      flash[:notice] = "#{t('.succes')} - #{ActionController::Base.helpers.link_to(t('.result'), @result.url, target: '_blank')}".html_safe
Я перечитал весь материл, который нашел. Я перепробывал все варианты, которые знал. Но Rails экранирует ссылку и все.

2023-10-21 02:15 UTC, Vlad2088 commented on app/controllers/gists_controller.rb
> +      flash[:notice] = "#{t('.succes')} - #{ActionController::Base.helpers.link_to(t('.result'), @result.url, target: '_blank')}".html_safe
Исправил. Теперь работает

2023-10-21 21:15 UTC, VidgarVii requested changes

2023-10-21 21:15 UTC, VidgarVii commented on .gitignore
> +/config/application.yml
секреты скрыты, это хорошо. Но другому разработчику надо понять какие ЕНВ нужны для проекта.
По этому надо добавить файл application.yml.example, который будет содержать пустые ЕНВ

2023-10-21 21:15 UTC, VidgarVii commented on app/controllers/gists_controller.rb
> +    if @result.success = true
тут всегда будет true
Не проще сделать объект который имеет метод success? который и будет отвечать на вопрос успешно ли отработал сервис? А не размазывать логику м/у сервисом и контроллером

2023-10-21 21:15 UTC, VidgarVii commented on app/controllers/gists_controller.rb
> +      flash[:notice] = "#{t('.succes')} - #{ActionController::Base.helpers.link_to(t('.result'), @result.url, target: '_blank')}"
как-то сложно.
в i18n можно писать хтмл
https://rusrails.ru/i18n#ispolzovanie-html-bezopasnyh-perevodov

2023-10-21 21:15 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +  before_action :set_test_passage, only: %i[show update result gist]
не используемый код надо удалять

2023-10-21 21:15 UTC, VidgarVii commented on app/services/gist_quesnion_servise.rb
> +  end
еще можно так:
```ruby
[@question.body, *@question.answers.pluck(:body)].join("\n")
```
уменьшит потребление памяти и выглядит лучше

2023-10-22 11:32 UTC, VidgarVii requested changes

2023-10-22 11:32 UTC, VidgarVii commented on app/controllers/gists_controller.rb
> +    if @result.success
у предикатных методов в названии должен быть знак вопроса
success?

2023-10-22 11:32 UTC, VidgarVii commented on app/services/gist_quesnion_servise.rb
> +    Struct::GistObject.new(response.html_url, @client.success?)
у клиента есть такой метод? success?
точно код был протестирован?

2023-10-22 11:53 UTC, Vlad2088 commented on app/services/gist_quesnion_servise.rb
> +    Struct::GistObject.new(response.html_url, @client.success?)
в  GitHubClient я прописал метод success?

2023-10-22 11:56 UTC, Vlad2088 commented on app/controllers/gists_controller.rb
> +    if @result.success
сам метод возвращает ссылку и success=true. Если я ствлю знак вопроса, то он выбравыет исключение: undefined method `success?' for #<struct Struct::GistObject url="https://gist.github.com/Vlad2088/a1024940c493d091f90e1e8a59e0fcb8", success=true>

2023-10-23 01:23 UTC, Vlad2088 commented on app/controllers/gists_controller.rb
> +    if @result.success == true
У класса Struct нет метода "success?", но есть оператор сравнения. @result.success возвращаяет ссылку и success = true (#<struct Struct::GistObject url="https://gist.github.com/Vlad2088/8175cef6b43746dc8d4bcc9afd215236", success=true>). Код я проверил, если изменить true на false в методе, то отрабатывает else.

2023-10-23 01:26 UTC, Vlad2088 commented on app/controllers/gists_controller.rb
> +    if @result.success == true
А сам метод success, я объявил изначально в GitHubClient. ПРосто при первом ПЛ я по запарке сделал присваивание, а не сравнение.

2023-10-23 04:59 UTC, VidgarVii requested changes

2023-10-23 04:59 UTC, VidgarVii commented on app/controllers/gists_controller.rb
> +    if @result.success == true
вот эта праверка реализована не корректно. Тем более проверяется 2 раза. Тут и в сервисе. Зачем использовать оператор сравнения тут если можно просто создать предикатный метод **#success?**

2023-10-23 04:59 UTC, VidgarVii commented on lib/clients/git_hub_client.rb
> +class GitHubClient
сразу не понял что ты обернул Octokit::Client в другой класс. Не понятно только зачем. Мы не пишем свой хттпл клиент. Мы используем уже готовый Octokit::Client

2023-10-23 14:13 UTC, VidgarVii commented on app/services/gist_quesnion_servise.rb
> +  ACCESS_TOKEN = ENV["github_token"].freeze
ЕНВ как и константы пишут большими буквами

2023-10-23 14:13 UTC, VidgarVii commented on app/services/gist_quesnion_servise.rb
> +      status_server == SERVER_RESPONSE
Не очень получается, что данный объект зависит от данных другого объекта. Это я про константу SERVER_RESPONSE. Почему она объявлена не тут?

2023-10-23 20:52 UTC, Vlad2088 commented on app/services/gist_quesnion_servise.rb
> +  ACCESS_TOKEN = ENV["github_token"].freeze
Исправил.

2023-10-23 20:58 UTC, Vlad2088 commented on app/services/gist_quesnion_servise.rb
> +      status_server == SERVER_RESPONSE
Я определил там статус ответа сервера и использовал метод freeze, чтоб заблокировать ее от изменений

2023-10-24 10:34 UTC, merged