create_models_and_migrate
Vlad2088/test_guru pull request #2
Opened 2023-07-06 07:00 UTC by Vlad2088

2023-07-06 15:19 UTC, VidgarVii requested changes

2023-07-06 15:19 UTC, VidgarVii commented on db/migrate/20230706031240_create_tests.rb
> +      t.integer :category_id, index: true
для связей м/у таблицами нужны не обычные поля, а с указанием создания внешних ключей
для этого деже есть метод references

2023-07-06 15:19 UTC, VidgarVii commented on db/migrate/20230706031240_create_tests.rb
> +      t.integer :category_id, index: true
для теста нам еще понадобиться автор. Это юзер который создал тест. Но при этом по названию колонки должно быть понятно, что речь идёт именно об авторе теста. Предлагаю это сделать в текущем ПР.

2023-07-06 15:19 UTC, VidgarVii commented on db/migrate/20230706031240_create_tests.rb
> +      t.integer :level, default: 0
null: false

2023-07-06 15:19 UTC, VidgarVii commented on db/migrate/20230706031337_create_answers.rb
> +      t.boolean :correct, default: false
для логических полей рекомендуется указывать опцию `null: false`
тогда в базе будут возможны строго два значения `true` или `false` вместо трех (`null/true/false`)

2023-07-06 21:06 UTC, Vlad2088 commented on db/migrate/20230706031240_create_tests.rb
> +      t.integer :level, default: 0
В задании было установить значение по умолчанию, зачем нужен "null: false"?

2023-07-07 05:47 UTC, VidgarVii commented on db/migrate/20230706031240_create_tests.rb
> +      t.integer :level, default: 0
это так же в тз прописано. Да и зачем давать возможно оставлять пустые строки? Мы не планируем создавать тесты без уровней

2023-07-09 06:53 UTC, VidgarVii requested changes

2023-07-09 06:53 UTC, VidgarVii commented on app/models/answer.rb
> +  belongs_to :question
ассоциации позже будут в курсе
пока лучше убери их из моделей, чтобы они не отвлекали. Тем более они объявлены не верно.
Нам на данном этапе внешних ключей в таблицах вполне достаточно ближайшие пару уроков нужно будет ручками конструировать запросы, чтобы лучше понять, как ассоциации работают, а потом уже будем использовать ассоциации

2023-07-09 06:53 UTC, VidgarVii commented on db/migrate/20230706031240_create_tests.rb
> +      t.string :autor, null: false
автор  это пользователь, который создал тест. Таблица пользователей уже есть. Значит надо создать связь с этой таблицей оставив понятное название поле и добавить null false 

Еще автор написано с ошибкой

2023-07-09 06:53 UTC, VidgarVii commented on db/migrate/20230706031240_create_tests.rb
> +      t.belongs_to :category
для ссылочной целостности данных всегда надо добавлять внешний ключ
И опять не хватает null false

2023-07-09 06:53 UTC, VidgarVii commented on db/migrate/20230706031240_create_tests.rb
> +      t.belongs_to :user
что это за связь?

2023-07-09 06:53 UTC, VidgarVii commented on db/migrate/20230706031410_create_users.rb
> +      t.string :context, null: false
это поле точно не обхадимо? что оно будет содержать?

2023-07-16 03:42 UTC, merged